### ISSUE TITLE
Windows环境下hexo generate报错XXX is not a function

### ISSUE THREAD

**Issue by chanwj** [Cerallin/hexo-theme-yuzu#24]
从零开始新建的博客，按照README.MD的指示安装了主题并增加了对应的配置，但是在hexo g这一步就开始报错，有好几条是“XXX is not a function”，一条是"cannot coerce content-max-width to unit"。
具体报错信息举例如下，请问是我哪里没有设置对么？

``` shell
TypeError: D:\hexo\blog\themes\hexo-theme-yuzu\layout\post.pug:1
  > 1| | !{ partial('_partial/article', {post: page}) }
    2|
    3| if theme.toc.enable
    4|   | !{ partial('_partial/post/toc', {post: page}) }

D:\hexo\blog\themes\hexo-theme-yuzu\layout\_partial\article.pug:13
    11|
    12|   .post-info
  > 13|     | !{ partial('_partial/post/word-count', {post: post}) }
    14|     | !{ partial('_partial/post/copyright', {post: post}) }
    15|
    16|   .article-entry(itemprop="articleBody")

D:\hexo\blog\themes\hexo-theme-yuzu\layout\_partial\post\word-count.pug:1
  > 1| -
    2|   const words = word_counter(post.content);
    3|   const word_count = (function (words) {
    4|     const { mode } = theme.word_count;

word_counter is not a function
    at eval (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:8:15)
    at template (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:32:7)
    at _View._compiledSync (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (D:\hexo\blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:32:46)
    at template (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:59:7)
    at _View._compiledSync (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (D:\hexo\blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:8:46)
    at template (eval at wrap (D:\hexo\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:14:7)
    at _View._compiled (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:123:67)
    at _View.render (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:48:21)
    at D:\hexo\blog\node_modules\hexo\dist\hexo\index.js:60:29
    at tryCatcher (D:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\hexo\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\hexo\blog\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:737:12)
    at resume_ (node:internal/streams/readable:1255:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

``` shell
Asset render failed: css/search.css
CoercionError: D:\hexo\blog\themes\hexo-theme-yuzu\source\css\search.styl:17:23
   13|
   14|   .card
   15|     position: relative
   16|     width: 60dvw
   17|     max-width: (2/3 * content-max-width)
-----------------------------^
   18|     height: 60dvh
   19|     margin-left: auto
   20|     margin-right: auto

cannot coerce content-max-width to unit
    at ".card" (D:\hexo\blog\themes\hexo-theme-yuzu\source\css\search.styl:15:3)
    at ".search-modal" (D:\hexo\blog\themes\hexo-theme-yuzu\source\css\search.styl:2:1)

    at Unit.coerce (D:\hexo\blog\node_modules\stylus\lib\nodes\node.js:247:11)
    at Unit.coerce (D:\hexo\blog\node_modules\stylus\lib\nodes\unit.js:207:20)
    at Unit.operate (D:\hexo\blog\node_modules\stylus\lib\nodes\unit.js:127:22)
    at Evaluator.visitBinOp (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:575:30)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitExpression (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:638:28)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitExpression (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:638:28)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitProperty (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:683:24)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitBlock (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:716:41)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitGroup (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:255:24)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitBlock (D:\hexo\blog\node_modules\stylus\lib\visitor\evaluator.js:716:41)

```

**Comment by Cerallin** [comment]
1. `word_counter is not a function` 试试 `hexo clean && hexo generate`。如果还不行的话需要请你附上你的`package.json`，谢谢~
2. `cannot coerce content-max-width to unit` 是一个known issue，不影响HTML生成（虽然我还没处理）。

**Comment by chanwj** [comment]
@Cerallin hexo clean已经试过，还是一样报错呢。除了word_counter之外，还有group_posts、item_url等也报错not a function，看起来是pug-helpers的script未生效？

以下是`package.json`的内容

``` json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.1.1"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-search": "^2.4.3",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
}

```

**Comment by flottant** [comment]
遇到了同样的问题。
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0"
  }
}

```

**Comment by Cerallin** [comment]
> @Cerallin hexo clean已经试过，还是一样报错呢。除了word_counter之外，还有group_posts、item_url等也报错not a function，看起来是pug-helpers的script未生效？

是的，看起来是hexo启动的时候没能成功调用`scripts/pug-helpers.js`，或者该文件里的代码没有正确执行。我尝试了`hexo 7.0.0`和`hexo 7.1.1`，但都不能复现这个问题。

也有一种可能是npm的缓存有问题，比如你们之前切换了hexo版本之类的，这种情况 `npm cache clean -f` 可以解决问题。（顺便一提 `-f` 需谨慎）

如果还是不行，希望你帮我尝试检查一下`scripts/pug-helpers.js`，例如在这这里加一行`console.debug(hexo.theme_dir)`然后看看日志，非常感谢。

https://github.com/Cerallin/hexo-theme-yuzu/blob/e68de7dc8b4c2140fe2f39a0a741e3baf25f5c8b/scripts/pug-helpers.js#L22-L25

**Comment by chanwj** [comment]
> 是的，看起来是hexo启动的时候没能成功调用`scripts/pug-helpers.js`，或者该文件里的代码没有正确执行。我尝试了`hexo 7.0.0`和`hexo 7.1.1`，但都不能复现这个问题。
> 
> 也有一种可能是npm的缓存有问题，比如你们之前切换了hexo版本之类的，这种情况 `npm cache clean -f` 可以解决问题。（顺便一提 `-f` 需谨慎）
> 
> 如果还是不行，希望你帮我尝试检查一下`scripts/pug-helpers.js`，例如在这这里加一行`console.debug(hexo.theme_dir)`然后看看日志，非常感谢。

@Cerallin 

1.我是昨天新下载安装的npm和hexo，未经历过版本切换；另外尝试过`npm cache clean -f`，情况还是一样。

2.使用`--debug`模式看见如下信息：
``` shell
07:54:02.636 DEBUG Script loaded: themes\hexo-theme-yuzu\scripts\pug-helpers.js
……
07:54:02.897 DEBUG Processed: layout/_partial/post/word-count.pug
……
```
但未见其他额外的报错内容；在`scripts/pug-helpers.js`中加入`console.debug(hexo.theme_dir)`后未见新的调试信息，也没看到生成log文件。（抱歉，我对这套东西不熟，可能没用对方法？\_(:з」∠)\_ ）

**Comment by Cerallin** [comment]
大家好，我写的CI通过了。目前我认为该问题不是本主题引起的，但是我还是非常愿意帮助大家解决问题。

目前我推测是**哪个环节的缓存**出了问题，例如node、npm、hexo的缓存。

**Comment by flottant** [comment]
> 大家好，我写的CI通过了。目前我认为该问题不是本主题引起的，但是我还是非常愿意帮助大家解决问题。
> 
> 目前我推测是**哪个环节的缓存**出了问题，例如node、npm、hexo的缓存。

那能否恳请分享您使用的环境信息？我再进行一下尝试。

**Comment by flottant** [comment]
我在 ubuntu 22.04 LTS 重新进行了尝试，没有出现报错，因此可能怀疑是 Windows 的问题？

**Comment by chanwj** [comment]
补充：切换到v2.x版本可用

**Comment by Cerallin** [comment]
@chanwj 你也是Windows环境下出现了问题吗？

Edit: CI的windows build可以复现问题了。

终于复现了。

**Comment by chanwj** [comment]
> @chanwj 你也是Windows环境下出现了问题吗？
> 
> Edit: CI的windows build可以复现问题了。
> 
> 终于复现了。

@Cerallin 是的，我用的Windows环境。

现在的版本可以正常运行了，谢谢大佬~
